[2023-12-09 18:47:10,315] ERROR log_exception() L1449 Exception on /apanhado [POST] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py", line 88, in predict
    id=form.id,
AttributeError: 'ApanhadoSchema' object has no attribute 'id'
[2023-12-09 18:47:10,318] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:47:10] "[35m[1mPOST /apanhado HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:47:12,510] ERROR log_exception() L1449 Exception on /apanhado [POST] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py", line 88, in predict
    id=form.id,
AttributeError: 'ApanhadoSchema' object has no attribute 'id'
[2023-12-09 18:47:12,511] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:47:12] "[35m[1mPOST /apanhado HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:47:26,795] INFO _log() L224   * Detected change in '/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py', reloading - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:47:30,383] ERROR log_exception() L1449 Exception on /apanhado [POST] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py", line 87, in predict
    apanhado = Apanhado(
TypeError: __init__() missing 1 required positional argument: 'id'
[2023-12-09 18:47:30,386] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:47:30] "[35m[1mPOST /apanhado HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:12,334] INFO _log() L224   * Detected change in '/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py', reloading - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:22,781] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.2.15:5000 (Press CTRL+C to quit) - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:22,782] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:24,744] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:48:24] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:24,825] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:48:24] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:24,827] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:48:24] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:24,829] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:48:24] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:25,005] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:48:25] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:48:33,085] ERROR log_exception() L1449 Exception on /apanhado [POST] - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/home/filipiayres/.local/lib/python3.10/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py", line 86, in predict
    apanhado = Apanhado(
TypeError: __init__() missing 1 required positional argument: 'id'
[2023-12-09 18:48:33,087] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:48:33] "[35m[1mPOST /apanhado HTTP/1.1[0m" 500 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:49:17,037] INFO _log() L224   * Detected change in '/home/filipiayres/√Årea de Trabalho/MVP-engenharia-de-software/api cardio/app.py', reloading - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:49:17,191] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:49:18,982] INFO _log() L224  10.0.2.15 - - [09/Dec/2023 18:49:18] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
[2023-12-09 18:50:29,734] INFO _log() L224   * Restarting with stat - call_trace=/home/filipiayres/.local/lib/python3.10/site-packages/werkzeug/_internal.py L224 
